vscode:
  extensions:
    - coenraads.bracket-pair-colorizer@1.0.61:+jQByqALW0iXkhpd2yzYzQ==
    - dsznajder.es7-react-js-snippets@3.1.1:3r85sshgGXBFhEFjBIyk3Q==
    - oderwat.indent-rainbow@7.5.0:CpN4cZnk34gVihISgY/1Qw==
    - ritwickdey.liveserver@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - silvenon.mdx@0.1.0:noyEQOpEjktPkFXA4qp72g==
    - esbenp.prettier-vscode@6.3.1:iOVHVb01wildbNZ98o51fQ==
    - svelte.svelte-vscode@104.8.0:82wQ4G6veIE3KBUYHpHgmw==
    - fivethree.vscode-svelte-snippets@0.5.0:rRkcaFrMb8wbTuH6kbGEQQ==
    - jpoissonnier.vscode-styled-components@1.5.0:NW+sYHi2vMBkmIuiABFSmQ==
    - mikestead.dotenv@1.0.1:mOYTwK5n1igNraaENZzWPQ==
    - yuichinukiyama.vscode-preview-server@1.3.0:DnqKp9GoPZ4JlgnrXXMhaQ==
    - wallabyjs.quokka-vscode@1.0.353:qyE0f9LXbEacl3UWvizaZQ==
    - ardenivanov.svelte-intellisense@0.7.1:yvZK5uYo4UxR2e0YO/Lmiw==